name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.3.0=pyhd8ed1ab_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h2aa6e3c_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py310hca03da5_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - bottleneck=1.4.2=py310hbda83bc_0
  - brotli-python=1.1.0=py310h1253130_1
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2025.9.9=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py310hca03da5_0
  - cffi=1.16.0=py310hdcd7c05_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=23.3.1=py310hca03da5_0
  - conda-content-trust=0.1.3=py310hca03da5_0
  - conda-package-handling=1.9.0=py310h8e9501a_1
  - cryptography=42.0.7=py310ha71c378_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.1=py310h692a8b6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fontconfig=2.15.0=h29935d0_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.22.5=h8fbad5d_2
  - gettext-tools=0.22.5=h8fbad5d_2
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py310hca03da5_0
  - harfbuzz=10.2.0=he637ebf_1
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - ipython_genutils=0.2.0=py_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9f=h2f69dba_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hbe9552e_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=py310hca03da5_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hbe9552e_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.4.7=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libasprintf=0.22.5=h8fbad5d_2
  - libasprintf-devel=0.22.5=h8fbad5d_2
  - libavif=1.1.1=h80987f9_0
  - libcxx=17.0.6=h5f092b4_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.22.5=h8fbad5d_2
  - libgettextpo-devel=0.22.5=h8fbad5d_2
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.7=h93a5062_0
  - libintl=0.22.5=h8fbad5d_2
  - libintl-devel=0.22.5=h8fbad5d_2
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.3=h091b4b1_0
  - libtiff=4.7.0=h91aec0a_0
  - libunistring=0.9.10=h3422bc3_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.5=py310hd125d64_0
  - matplotlib-base=3.10.6=py310h066045a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.4=hd8ed1ab_0
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=6.5.4=py310hecd8cb5_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numexpr=2.11.0=py310h8c72970_1
  - numpy-base=2.1.3=py310hae06d03_2
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.3.0=h0d3ecfb_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandoc=3.1.13=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.46.4=h09dc60e_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py310hd125d64_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycosat=0.6.6=py310h2aa6e3c_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.2=py310hb3aa912_0
  - pyobjc-framework-cocoa=10.2=py310hb3aa912_0
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=h2469fbe_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python.app=3=py310h1a28f6b_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=26.0.3=py310h16e08c9_0
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.1=py310h947b723_0
  - ruamel.yaml=0.17.40=py310hd125d64_0
  - ruamel.yaml.clib=0.2.8=py310hd125d64_0
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py310hd125d64_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wget=1.21.4=he2df1f1_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=h5119023_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.6=hfb09047_0
  - pip:
      - alembic==1.13.1
      - async-generator==1.10
      - bokeh==3.6.3
      - certipy==0.1.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - eqtk==0.1.3
      - filelock==3.14.0
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - joblib==1.4.2
      - jupyter-telemetry==0.1.0
      - jupyterhub==4.0.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - mako==1.3.0
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - nbformat==5.9.2
      - networkx==3.3
      - numba==0.58.1
      - numpy==1.26.1
      - nupack==4.0.2.0
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - pamela==1.1.0
      - pandas==2.2.0
      - pillow==10.3.0
      - pyparsing==3.1.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - sqlalchemy==2.0.25
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torchvision==0.18.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - xyzservices==2025.10.0
prefix: /Users/jamiekwon/miniconda3
